version: '3.5'

services:

  generator:
    build: .
    image: abilioesteves/metrics-generator:latest
    ports:
      - 32865:32865
    environment:
      - REGISTRY_ETCD_URL=http://etcd:2379

  etcd:
    image: quay.io/coreos/etcd:v3.2.25
    ports:
      - 2379
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379


